# /etc/apache2/sites-available/sqli-demo.conf

<VirtualHost *:80>
    DocumentRoot /var/www/html

    SecRuleEngine On

    <Directory /var/www/html>
        Options -Indexes
        AllowOverride None
        Require all granted
    </Directory>

    <Location /process1.php>
        SecRuleEngine Off
    </Location>

    <Location /process2.php>
        SecRuleEngine On
    </Location>

    <Directory /var/www/html/db>
        Require all denied
    </Directory>

    ErrorLog  ${APACHE_LOG_DIR}/sqli-demo-error.log
    CustomLog ${APACHE_LOG_DIR}/sqli-demo-access.log combined
</VirtualHost>
